// var caribbeanUrl = {
// 	"Aruba":"http://www.gobierno.aw/",
// 	"Anguilla":"http://www.gov.ai/",
// 	"Antigua and Barbuda":"http://www.ab.gov.ag/",
// 	"Bahamas":"http://www.bahamas.gov.bs/",
// 	"Saint Barthélemy":"http://www.comstbarth.fr/",
// 	"Barbados":"https://www.gov.bb/",
// 	"Cuba":"http://www.cubagob.cu/",
// 	"Curaçao":"http://www.gobiernu.cw/",
// 	"Cayman Islands":"http://www.gov.ky/",
// 	"Dominica":"http://www.dominica.gov.dm/",
// 	"Dominican Republic":"http://www.presidencia.gov.do/",
// 	"Guadeloupe":"http://www.regionguadeloupe.fr/",
// 	"Grenada":"http://www.gov.gd/",
// 	"Haiti":"http://primature.gouv.ht/",
// 	"Jamaica":"http://jis.gov.jm/",
// 	"Saint Kitts and Nevis":"http://sknis.info/",
// 	"Saint Lucia":"http://www.govt.lc/",
// 	"Saint Martin":"http://www.com-saint-martin.fr/Pages/Bienvenue.aspx",
// 	"Montserrat":"http://www.gov.ms/",
// 	"Martinique":"http://www.martinique.pref.gouv.fr/",
// 	"Puerto Rico":"http://www2.pr.gov/Pages/default.aspx",
// 	"Sint Maarten":"http://www.sintmaartengov.org/Pages/default.aspx",
// 	"Turks and Caicos Islands":"http://www.gov.tc/",
// 	"Trinidad and Tobago":"http://www.ttconnect.gov.tt/",
// 	"Saint Vincent and the Grenadines":"http://www.gov.vc/",
// 	"British Virgin Islands":"http://www.bvi.gov.vg/",
// 	"United States Virgin Islands":"https://www.vi.gov/"
// };
// var cca2Array = [AW,
// AI,
// AG,
// BS,
// BL,
// BB,
// CU,
// CW,
// KY,
// DM,
// DO,
// GP,
// GD,
// HT,
// JM,
// KN,
// LC,
// MF,
// MS,
// MQ,
// PR,
// SX,
// TC,
// TT,
// VC,
// VG,
// VI];